spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/exam
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      jdbc:
        lob:
          non_contsxtual_creation: true